USE DATABASE NEXAMART_DB;
USE SCHEMA NEXAMART_SILVER;
USE WAREHOUSE NEXAMART_WH;

CREATE OR REPLACE TABLE ANOMALY_RESOLUTION_SUMMARY AS
SELECT 
    'A1' AS ANOMALY_CODE, 'CANCELLED_ORDER_IN_REVENUE' AS ANOMALY_NAME, 'A' AS CATEGORY, 
    COUNT(*) AS TOTAL_FLAGGED, SUM(IFF(RESOLUTION_APPLIED=TRUE, 1, 0)) AS SUCCESSFULLY_RESOLVED
FROM (
    SELECT RESOLUTION_APPLIED FROM EC_ORDERS WHERE ANOMALY_REASON_CODE LIKE '%CANCELLED_ORDER_IN_REVENUE%'
    UNION ALL
    SELECT RESOLUTION_APPLIED FROM POS_TRANSACTIONS WHERE ANOMALY_REASON_CODE LIKE '%CANCELLED_ORDER_IN_REVENUE%'
)
UNION ALL
SELECT 'A2', 'PAYMENT_CAPTURED_AFTER_CANCELLATION', 'A', COUNT(*), SUM(IFF(RESOLUTION_APPLIED=TRUE, 1, 0))
FROM PG_TRANSACTIONS WHERE ANOMALY_REASON_CODE LIKE '%PAYMENT_CAPTURED_AFTER_CANCELLATION%'
UNION ALL
SELECT 'A3', 'TAX_SHIPPING_INCLUSION_MISMATCH', 'A', COUNT(*), SUM(IFF(RESOLUTION_APPLIED=TRUE, 1, 0))
FROM POS_TRANSACTIONS WHERE ANOMALY_REASON_CODE LIKE '%TAX_SHIPPING_INCLUSION_MISMATCH%'
UNION ALL
SELECT 'A4', 'NEXALOCAL_SOLD_AS_CONFIRMED_REVENUE', 'A', COUNT(*), SUM(IFF(RESOLUTION_APPLIED=TRUE, 1, 0))
FROM NL_LISTING_EVENTS WHERE ANOMALY_REASON_CODE LIKE '%NEXALOCAL_SOLD_AS_CONFIRMED_REVENUE%'
UNION ALL
SELECT 'A5', 'ATP_MISMATCH_WEBSITE_VS_WAREHOUSE', 'A', COUNT(*), SUM(IFF(RESOLUTION_APPLIED=TRUE, 1, 0))
FROM WH_INVENTORY_SNAPSHOTS WHERE ANOMALY_REASON_CODE LIKE '%ATP_MISMATCH_WEBSITE_VS_WAREHOUSE%'
UNION ALL
SELECT 'A6', 'NEGATIVE_ATP', 'A', COUNT(*), SUM(IFF(RESOLUTION_APPLIED=TRUE, 1, 0))
FROM (
    SELECT RESOLUTION_APPLIED FROM SI_INVENTORY_SNAPSHOTS WHERE ANOMALY_REASON_CODE LIKE '%NEGATIVE_ATP%'
    UNION ALL
    SELECT RESOLUTION_APPLIED FROM WH_INVENTORY_SNAPSHOTS WHERE ANOMALY_REASON_CODE LIKE '%NEGATIVE_ATP%'
)
UNION ALL
SELECT 'A7', 'RETURNED_STOCK_COUNTED_BEFORE_INSPECTION', 'A', COUNT(*), SUM(IFF(RESOLUTION_APPLIED=TRUE, 1, 0))
FROM RR_RETURN_RECEIPTS WHERE ANOMALY_REASON_CODE LIKE '%RETURNED_STOCK_COUNTED_BEFORE_INSPECTION%'
UNION ALL
SELECT 'A8', 'MISSING_INVENTORY_SNAPSHOT_DAY', 'A', COUNT(*), SUM(IFF(RESOLUTION_APPLIED=TRUE, 1, 0))
FROM SI_INVENTORY_SNAPSHOTS WHERE ANOMALY_REASON_CODE LIKE '%MISSING_INVENTORY_SNAPSHOT_DAY%'
UNION ALL
SELECT 'A9', 'SKU_MAPPED_TO_DIFFERENT_PRODUCTS', 'A', COUNT(*), SUM(IFF(RESOLUTION_APPLIED=TRUE, 1, 0))
FROM TS_SELLER_LISTINGS WHERE ANOMALY_REASON_CODE LIKE '%SKU_MAPPED_TO_DIFFERENT_PRODUCTS%'
UNION ALL
SELECT 'A10', 'OPEN_BOX_SOLD_AS_NEW', 'A', COUNT(*), SUM(IFF(RESOLUTION_APPLIED=TRUE, 1, 0))
FROM RR_RETURN_RECEIPTS WHERE ANOMALY_REASON_CODE LIKE '%OPEN_BOX_SOLD_AS_NEW%'
UNION ALL
SELECT 'A11', 'PLACEHOLDER_CUSTOMER_ID_COLLISION', 'A', COUNT(*), SUM(IFF(RESOLUTION_APPLIED=TRUE, 1, 0))
FROM EC_ORDERS WHERE ANOMALY_REASON_CODE LIKE '%PLACEHOLDER_CUSTOMER_ID_COLLISION%'
UNION ALL
SELECT 'A12', 'LISTING_SOLD_THEN_RELISTED', 'A', COUNT(*), SUM(IFF(RESOLUTION_APPLIED=TRUE, 1, 0))
FROM (
    SELECT RESOLUTION_APPLIED FROM NL_LISTINGS WHERE ANOMALY_REASON_CODE LIKE '%LISTING_SOLD_THEN_RELISTED%'
    UNION ALL
    SELECT RESOLUTION_APPLIED FROM NL_LISTING_EVENTS WHERE ANOMALY_REASON_CODE LIKE '%LISTING_SOLD_THEN_RELISTED%'
)
UNION ALL
SELECT 'A13', 'COORDINATED_FAKE_LISTING_RING', 'A', COUNT(*), SUM(IFF(RESOLUTION_APPLIED=TRUE, 1, 0))
FROM (
    SELECT RESOLUTION_APPLIED FROM NL_USER_ACCOUNTS WHERE ANOMALY_REASON_CODE LIKE '%COORDINATED_FAKE_LISTING_RING%'
    UNION ALL
    SELECT RESOLUTION_APPLIED FROM NL_LISTINGS WHERE ANOMALY_REASON_CODE LIKE '%COORDINATED_FAKE_LISTING_RING%'
    UNION ALL
    SELECT RESOLUTION_APPLIED FROM NL_LISTING_EVENTS WHERE ANOMALY_REASON_CODE LIKE '%COORDINATED_FAKE_LISTING_RING%'
)
UNION ALL
SELECT 'A14', 'DELIVERED_BEFORE_SHIPPED', 'A', COUNT(*), SUM(IFF(RESOLUTION_APPLIED=TRUE, 1, 0))
FROM DC_DELIVERY_EVENTS WHERE ANOMALY_REASON_CODE LIKE '%DELIVERED_BEFORE_SHIPPED%'
UNION ALL
SELECT 'A15', 'REVIEW_BEFORE_DELIVERY', 'A', COUNT(*), SUM(IFF(RESOLUTION_APPLIED=TRUE, 1, 0))
FROM RV_REVIEWS WHERE ANOMALY_REASON_CODE LIKE '%REVIEW_BEFORE_DELIVERY%'
UNION ALL
SELECT 'A16', 'DUPLICATE_COMPLAINT_CASE', 'A', COUNT(*), SUM(IFF(RESOLUTION_APPLIED=TRUE, 1, 0))
FROM CS_CASES WHERE ANOMALY_REASON_CODE LIKE '%DUPLICATE_COMPLAINT_CASE%'

-- CATEGORY B
UNION ALL
SELECT 'B1', 'CAMPAIGN_ATTRIBUTION_AMBIGUOUS', 'B', COUNT(*), SUM(IFF(RESOLUTION_APPLIED=TRUE, 1, 0))
FROM EC_ORDERS WHERE ANOMALY_REASON_CODE LIKE '%CAMPAIGN_ATTRIBUTION_AMBIGUOUS%'
UNION ALL
SELECT 'B2', 'PARTIAL_REFUND_PERIOD_AMBIGUOUS', 'B', COUNT(*), SUM(IFF(RESOLUTION_APPLIED=TRUE, 1, 0))
FROM RR_REFUND_EVENTS WHERE ANOMALY_REASON_CODE LIKE '%PARTIAL_REFUND_PERIOD_AMBIGUOUS%'
UNION ALL
SELECT 'B3', 'INVENTORY_MOVEMENT_NO_ORDER_REF', 'B', COUNT(*), SUM(IFF(RESOLUTION_APPLIED=TRUE, 1, 0))
FROM (
    SELECT RESOLUTION_APPLIED FROM SI_INVENTORY_MOVEMENTS WHERE ANOMALY_REASON_CODE LIKE '%INVENTORY_MOVEMENT_NO_ORDER_REF%'
    UNION ALL
    SELECT RESOLUTION_APPLIED FROM WH_INVENTORY_MOVEMENTS WHERE ANOMALY_REASON_CODE LIKE '%INVENTORY_MOVEMENT_NO_ORDER_REF%'
)
UNION ALL
SELECT 'B4', 'NEXALOCAL_PRODUCT_IDENTITY_AMBIGUOUS', 'B', COUNT(*), SUM(IFF(RESOLUTION_APPLIED=TRUE, 1, 0))
FROM NL_LISTINGS WHERE ANOMALY_REASON_CODE LIKE '%NEXALOCAL_PRODUCT_IDENTITY_AMBIGUOUS%'
UNION ALL
SELECT 'B5', 'CROSS_CHANNEL_IDENTITY_AMBIGUOUS', 'B', COUNT(*), SUM(IFF(RESOLUTION_APPLIED=TRUE, 1, 0))
FROM SILVER_CUSTOMER_MASTER WHERE ANOMALY_REASON_CODE LIKE '%CROSS_CHANNEL_IDENTITY_AMBIGUOUS%'
UNION ALL
SELECT 'B6', 'ESTIMATED_GMV_MODEL_AMBIGUOUS', 'B', COUNT(*), SUM(IFF(RESOLUTION_APPLIED=TRUE, 1, 0))
FROM NL_LISTING_EVENTS WHERE ANOMALY_REASON_CODE LIKE '%ESTIMATED_GMV_MODEL_AMBIGUOUS%'
UNION ALL
SELECT 'B7', 'BOPIS_PICKUP_CONFIRMATION_MISSING', 'B', COUNT(*), SUM(IFF(RESOLUTION_APPLIED=TRUE, 1, 0))
FROM EC_ORDERS WHERE ANOMALY_REASON_CODE LIKE '%BOPIS_PICKUP_CONFIRMATION_MISSING%'
UNION ALL
SELECT 'B8', 'SELLER_TRUST_SCORE_DESIGN_AMBIGUOUS', 'B', COUNT(*), SUM(IFF(RESOLUTION_APPLIED=TRUE, 1, 0))
FROM TS_SELLERS WHERE ANOMALY_REASON_CODE LIKE '%SELLER_TRUST_SCORE_DESIGN_AMBIGUOUS%';

-- FINAL SELECT
SELECT * FROM ANOMALY_RESOLUTION_SUMMARY ORDER BY CATEGORY, CAST(REPLACE(ANOMALY_CODE, CATEGORY, '') AS INT);
