-- 1. Database
CREATE DATABASE IF NOT EXISTS NEXAMART_DB
  COMMENT = 'NexaMart Enterprise Data Warehouse';

USE DATABASE NEXAMART_DB;

-- 2. Schemas
CREATE SCHEMA IF NOT EXISTS NEXAMART_BRONZE;
CREATE SCHEMA IF NOT EXISTS NEXAMART_SILVER;
CREATE SCHEMA IF NOT EXISTS NEXAMART_GOLD;
CREATE SCHEMA IF NOT EXISTS NEXAMART_MARTS;

-- 3. Warehouse 
CREATE WAREHOUSE IF NOT EXISTS NEXAMART_WH
  WITH WAREHOUSE_SIZE      = 'X-Small'
       AUTO_SUSPEND        = 60
       AUTO_RESUME         = TRUE
       INITIALLY_SUSPENDED = TRUE;

-- 4. Context Set
USE WAREHOUSE NEXAMART_WH;
USE DATABASE NEXAMART_DB;

-- 5. Verify
SHOW SCHEMAS IN DATABASE NEXAMART_DB;
SELECT 
    CURRENT_DATABASE()  AS database_name,
    CURRENT_WAREHOUSE() AS warehouse_name,
    CURRENT_SCHEMA()    AS schema_name;