USE DATABASE NEXAMART_DB;
USE SCHEMA NEXAMART_SILVER;
USE WAREHOUSE NEXAMART_WH;

SELECT * FROM (

    -- 1. ANOMALY DISTRIBUTION CHECKS
    -- Uses LATERAL FLATTEN to split comma-separated anomalies
    
    SELECT 'ANOMALY_DISTRIBUTION' AS check_type, 'EC_ORDERS' AS table_name, TRIM(f.value::string) AS metric_name, TO_VARCHAR(COUNT(*)) AS metric_value FROM EC_ORDERS, LATERAL FLATTEN(input => SPLIT(COALESCE(anomaly_reason_code, data_quality_status), ',')) f GROUP BY 1, 2, 3
    UNION ALL
    SELECT 'ANOMALY_DISTRIBUTION', 'POS_TRANSACTIONS', TRIM(f.value::string), TO_VARCHAR(COUNT(*)) FROM POS_TRANSACTIONS, LATERAL FLATTEN(input => SPLIT(COALESCE(anomaly_reason_code, data_quality_status), ',')) f GROUP BY 1, 2, 3
    UNION ALL
    SELECT 'ANOMALY_DISTRIBUTION', 'PG_TRANSACTIONS', TRIM(f.value::string), TO_VARCHAR(COUNT(*)) FROM PG_TRANSACTIONS, LATERAL FLATTEN(input => SPLIT(COALESCE(anomaly_reason_code, data_quality_status), ',')) f GROUP BY 1, 2, 3
    UNION ALL
    SELECT 'ANOMALY_DISTRIBUTION', 'RR_RETURN_RECEIPTS', TRIM(f.value::string), TO_VARCHAR(COUNT(*)) FROM RR_RETURN_RECEIPTS, LATERAL FLATTEN(input => SPLIT(COALESCE(anomaly_reason_code, data_quality_status), ',')) f GROUP BY 1, 2, 3
    UNION ALL
    SELECT 'ANOMALY_DISTRIBUTION', 'NL_LISTING_EVENTS', TRIM(f.value::string), TO_VARCHAR(COUNT(*)) FROM NL_LISTING_EVENTS, LATERAL FLATTEN(input => SPLIT(COALESCE(anomaly_reason_code, data_quality_status), ',')) f GROUP BY 1, 2, 3
    UNION ALL
    SELECT 'ANOMALY_DISTRIBUTION', 'TS_MARKETPLACE_ORDERS', TRIM(f.value::string), TO_VARCHAR(COUNT(*)) FROM TS_MARKETPLACE_ORDERS, LATERAL FLATTEN(input => SPLIT(COALESCE(anomaly_reason_code, data_quality_status), ',')) f GROUP BY 1, 2, 3
    UNION ALL
    SELECT 'ANOMALY_DISTRIBUTION', 'NL_LISTINGS', TRIM(f.value::string), TO_VARCHAR(COUNT(*)) FROM NL_LISTINGS, LATERAL FLATTEN(input => SPLIT(COALESCE(anomaly_reason_code, data_quality_status), ',')) f GROUP BY 1, 2, 3
    UNION ALL
    SELECT 'ANOMALY_DISTRIBUTION', 'TS_SELLERS', TRIM(f.value::string), TO_VARCHAR(COUNT(*)) FROM TS_SELLERS, LATERAL FLATTEN(input => SPLIT(COALESCE(anomaly_reason_code, data_quality_status), ',')) f GROUP BY 1, 2, 3

 
    -- 2. COMPLETENESS CHECKS (Matches Bronze?)

    UNION ALL
    SELECT 'COMPLETENESS', 'EC_ORDERS', 'silver_matches_bronze', TO_VARCHAR(CASE WHEN COUNT(*) = 963 THEN 'TRUE (963)' ELSE 'FALSE ('||COUNT(*)||')' END) FROM EC_ORDERS
    UNION ALL
    SELECT 'COMPLETENESS', 'POS_TRANSACTIONS', 'silver_matches_bronze', TO_VARCHAR(CASE WHEN COUNT(*) = 10868 THEN 'TRUE (10868)' ELSE 'FALSE ('||COUNT(*)||')' END) FROM POS_TRANSACTIONS
    UNION ALL
    SELECT 'COMPLETENESS', 'PG_TRANSACTIONS', 'silver_matches_bronze', TO_VARCHAR(CASE WHEN COUNT(*) = 963 THEN 'TRUE (963)' ELSE 'FALSE ('||COUNT(*)||')' END) FROM PG_TRANSACTIONS
    UNION ALL
    SELECT 'COMPLETENESS', 'RR_RETURN_RECEIPTS', 'silver_matches_bronze', TO_VARCHAR(CASE WHEN COUNT(*) = 74 THEN 'TRUE (74)' ELSE 'FALSE ('||COUNT(*)||')' END) FROM RR_RETURN_RECEIPTS
    UNION ALL
    SELECT 'COMPLETENESS', 'NL_LISTING_EVENTS', 'silver_matches_bronze', TO_VARCHAR(CASE WHEN COUNT(*) = 38706 THEN 'TRUE (38706)' ELSE 'FALSE ('||COUNT(*)||')' END) FROM NL_LISTING_EVENTS
    UNION ALL
    SELECT 'COMPLETENESS', 'TS_MARKETPLACE_ORDERS', 'silver_matches_bronze', TO_VARCHAR(CASE WHEN COUNT(*) = 252 THEN 'TRUE (252)' ELSE 'FALSE ('||COUNT(*)||')' END) FROM TS_MARKETPLACE_ORDERS


    -- 3. NULL DISTRIBUTION CHECKS

    UNION ALL
    SELECT 'NULL_DISTRIBUTION', 'EC_ORDERS', 'null_customer_id', TO_VARCHAR(SUM(CASE WHEN customer_id IS NULL THEN 1 ELSE 0 END)) FROM EC_ORDERS
    UNION ALL
    SELECT 'NULL_DISTRIBUTION', 'EC_ORDERS', 'null_order_status', TO_VARCHAR(SUM(CASE WHEN order_status IS NULL THEN 1 ELSE 0 END)) FROM EC_ORDERS
    UNION ALL
    SELECT 'NULL_DISTRIBUTION', 'POS_TRANSACTIONS', 'null_loyalty_card', TO_VARCHAR(SUM(CASE WHEN loyalty_card_number IS NULL THEN 1 ELSE 0 END)) FROM POS_TRANSACTIONS
    UNION ALL
    SELECT 'NULL_DISTRIBUTION', 'POS_TRANSACTIONS', 'null_status_code', TO_VARCHAR(SUM(CASE WHEN status_code IS NULL THEN 1 ELSE 0 END)) FROM POS_TRANSACTIONS
)
ORDER BY check_type, table_name, metric_name;